# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/swLEDcounter/swLEDcounter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter || ORIG_REF_NAME==swLEDcounter} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_clk_wiz_0_0 || ORIG_REF_NAME==swLEDcounter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_microblaze_0_0/swLEDcounter_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_microblaze_0_0 || ORIG_REF_NAME==swLEDcounter_microblaze_0_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_dlmb_v10_0/swLEDcounter_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_dlmb_v10_0 || ORIG_REF_NAME==swLEDcounter_dlmb_v10_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_ilmb_v10_0/swLEDcounter_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_ilmb_v10_0 || ORIG_REF_NAME==swLEDcounter_ilmb_v10_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_dlmb_bram_if_cntlr_0/swLEDcounter_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==swLEDcounter_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_ilmb_bram_if_cntlr_0/swLEDcounter_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==swLEDcounter_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_lmb_bram_0/swLEDcounter_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_lmb_bram_0 || ORIG_REF_NAME==swLEDcounter_lmb_bram_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_mdm_1_0/swLEDcounter_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_mdm_1_0 || ORIG_REF_NAME==swLEDcounter_mdm_1_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_rst_clk_wiz_0_100M_0/swLEDcounter_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==swLEDcounter_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_axi_gpio_0_2/swLEDcounter_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_axi_gpio_0_2 || ORIG_REF_NAME==swLEDcounter_axi_gpio_0_2} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_axi_gpio_0_3/swLEDcounter_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_axi_gpio_0_3 || ORIG_REF_NAME==swLEDcounter_axi_gpio_0_3} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_xbar_1/swLEDcounter_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_xbar_1 || ORIG_REF_NAME==swLEDcounter_xbar_1} -quiet] -quiet

# IP: bd/swLEDcounter/ip/swLEDcounter_microblaze_0_axi_periph_1/swLEDcounter_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swLEDcounter_microblaze_0_axi_periph_1 || ORIG_REF_NAME==swLEDcounter_microblaze_0_axi_periph_1} -quiet] -quiet

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/swLEDcounter_ooc.xdc
