# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.srcs/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0.xci
# IP: The module: 'swLEDcounter_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.srcs/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0.xci
# IP: The module: 'swLEDcounter_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_clk_wiz_0_0/swLEDcounter_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
