# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.srcs/sources_1/bd/swLEDcounter/ip/swLEDcounter_ilmb_v10_0/swLEDcounter_ilmb_v10_0.xci
# IP: The module: 'swLEDcounter_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_ilmb_v10_0/swLEDcounter_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.srcs/sources_1/bd/swLEDcounter/ip/swLEDcounter_ilmb_v10_0/swLEDcounter_ilmb_v10_0.xci
# IP: The module: 'swLEDcounter_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mkolb/Documents/Github/Basys3/project_1/project_1.gen/sources_1/bd/swLEDcounter/ip/swLEDcounter_ilmb_v10_0/swLEDcounter_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swLEDcounter_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
